name: UV5
favicon: null
layout_spectrum: 0.3643018533475697
typography_spectrum: 0.38922921218909323
title: The Official UV5 Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7583046827930957
  lightness: 0.27017145743593574
  saturation: 0.136825040448457
  rhythmicContrast: 0.7640850672032684
purpose: []
